### ISSUE TITLE
Unable to make IMSA-A run

### ISSUE THREAD

**Issue by eandresleon** [JeremyCoxBMI/IMSA-A#5]
Dear all I've tried to follow the instructions in the detail_directions.pdf with no success.

For example, we have to install imsa and IMSA-A .... then the pdf says: 
_IMSA+A files are placed in the imsa/ directory, where imsa was installed
To validate IMSA+A, run the pipeline on low.coverage.fa. In the example directory, you will find results for inchworm and oases, to which you can compare your results._

Does it mean that we have to overwrite the imsa files with the IMSA-A files ?

Then, I've understood that the reads are aligned using bowtie1 ( I'm unable to use bowtie2 as aligner) and those not aligned again the host (human in my case) are then filtered using blat/blast .... with the main goal to keep ONLY metagenomic reads. Nevertheless, the bowtie command that is run in the system does not use the -un /-un-con parameter, so unaligned reads are not been saved ... having a 0 blat result from 0 remaining reads.

So please, could you explain me what I'm doing wrong ?

Thanks in advance

**Comment by JeremyCoxBMI** [comment]
These instructions are incorrect!  As I recall, the original IMSA code had to be modified to update to use Accession Numbers.  So it is included here.  You can either overwrite the install, or just use the program contained here. 

There is a bug with the pipeline; if BLAT receives zero reads to process from the previous aligner, it throws an error code.
But you said you are having difficulty running BOWTIE.
The aligners you use depend upon the IMSA script you run.  Can you share your file?

If you want to use BOWTIE or any other aligner, you can run the command manually and use any filtering you like on your FA files before putting into the pipeline.  Indeed, part of the pipeline is an easier way to run all the alignments.  If it doesn't work properly, you can skip it.

**Comment by eandresleon** [comment]
Thanks @JeremyCoxBMI , In fact I have downloaded the code in this repo and now it is the one that I'm using. I'll try to explain everything step by step because I've obtained the same results.

I've created an action script (these files has been quality filtered): [action_script.txt](https://github.com/JeremyCoxBMI/IMSA-A/files/5400984/action_script.txt). Then I execute  python ../master.paired_end.py -i file1_R1.fq -j file1_R2.fq -p action_script.txt which creates a python script that I run having this error:

```
python pipelineScript.py
Running command: /home/eandres/bin/miARma/bin/Linux/bowtie/bowtie --quiet --sam --sam-nohead  -p 12 -p 12 /home/eandres/Projects/Externos/UGR/Signe/Revision/IMSA-A/human/bowtie/GRCh37 -1 file1_R1.fq -2 file1_R2.fq /mnt/beegfs/eandres/Projects/Externos/UGR/Signe/Revision/IM
SA-A.orig/test/file1_R1_chg.temp.bwt
Delimiter is '#0/' which is True
Running command: blat /home/eandres/Projects/Externos/UGR/Signe/Revision/IMSA-A/human/blat/GRCh37.2bit file1_R1_chg.combined_n5.fa  -fastMap -minIdentity=80 -ooc=/home/eandres/Projects/Externos/UGR/Signe/Revision/IMSA-A/human/blat/GRCh37.11.ooc  file1_R1_chg.combined_n5_ch
g.temp.psl
End of file reading 4 bytes
The last alignment result was found on line 0 of 0 (0.00% complete).  Approximately 0.00% of the queries are hits.
Found 0 hits in the blat results
Traceback (most recent call last):
  File "pipelineScript.py", line 63, in <module>
    pipelineUtils.filterUsingBlat("file1_R1_chg.combined_n5.fa", "file1_R1_chg.combined_n5_chg.psl", minPercent=None, minCoverage=None, minTotalPercent=0.8, delimiter='#0/', pairedHits=True, pairedMisses=False, printHits=None, printMisses='file1_R1_chg.combined_n5_chg
.temp.fa', divideHalf=False, mylistener=logFile)
  File "/home/eandres/Projects/Externos/UGR/Signe/Revision/IMSA-A/pipelineUtils.py", line 764, in filterUsingBlat
    mylistener)
  File "/home/eandres/Projects/Externos/UGR/Signe/Revision/IMSA-A/pipelineUtils.py", line 860, in doFilterUsingBlat
    raise Exception("The blat PSL file had no hits.  Stopping IMSA execution.")
Exception: The blat PSL file had no hits.  Stopping IMSA execution.
```

It says something about a delimiter: #0/ but I'dont know what is this. Then it fails in the blat process although I'm sure the error does not come from the blat. 

Nevertheless I have tried with my real samples and also with artificial samples ( 80% human, 10% pseudomonas and 10% Sinhorizobium) and the results is always the same.

If I check the script: [pipelineScript.py.zip](https://github.com/JeremyCoxBMI/IMSA-A/files/5401025/pipelineScript.py.zip) I see that the runBowtie() function works because it creates the file1_R1_chg.bwt file, but the filterUsingBowtie() must fail cause the file1_R1_chg.fq and file1_R2_chg.fq are empty.

So at this point I'm not sure what to do. Any recommendation ?
Thanks in advance

EDIT: I'm including the log file
[log_eandres_20_10_19_14_06_53.txt](https://github.com/JeremyCoxBMI/IMSA-A/files/5401691/log_eandres_20_10_19_14_06_53.txt)
